---
- name: Install st2
  hosts: all
  roles:
    - mongodb
    - rabbitmq
    - postgresql
    - st2repos
    - st2
    - st2mistral
    - nginx
    - st2web
    - nodejs
    - st2smoketests
    - bwc
    - bwc_smoketests
