---

- name: Assert that master_token is specified
  fail: msg="License key must be supplied for BWC enterprise installation."
  when: license is not defined

- name: Install prereqs (Debian)
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - debian-archive-keyring
    - apt-transport-https

- name: Get GPG key URL for private repo
  become: yes
  shell: 'curl "{{ deb_gpg_key_url }}"'
  register: deb_gpg_key

# This is the exact key as the open source repo but this behavior might change. So just
# following what's in packagecloud docs for private repos.
- name: Add GPG key to keyring
  become: yes
  shell: 'curl -L "{{ deb_gpg_key.stdout }}" | apt-key add -'
  when: ansible_os_family == "Debian" and license is defined

- name: "Adding packagecloud.io repository: StackStorm/{{ bwc_pkg_repo }} with generated read token"
  become: yes
  shell: 'curl "{{ deb_config_file_url }}" > {{ deb_config_file_location }}'
  args:
   creates: "{{ deb_config_file_location }}"
  register: added_bwc_deb_repository
  when: ansible_os_family == "Debian" and license is defined

- name: Update APT package cache
  become: yes
  apt:
    update_cache: true
  when: ansible_os_family == "Debian" and added_bwc_deb_repository|success
