---

- name: Assert that master_token is specified
  fail: msg="License key must be supplied for BWC enterprise installation."
  when: license is not defined

# Fixes "Failure talking to yum: Cannot retrieve repository metadata (repomd.xml) for repository: StackStorm_stable. Please verify its path and try again" when installing st2
- name: Update ca-certificates package
  become: yes
  yum:
    name: ca-certificates
    state: latest
  tags: skip_ansible_lint

# See: https://github.com/docker-library/docs/tree/master/centos#package-documentation
# We ship `nginx.conf` via `st2` package doc files, for example
- name: Enable shipping package documentation files for EL
  become: yes
  ini_file:
    dest: /etc/yum.conf
    section: main
    option: tsflags
    value: nodocs
    state: absent
  when: ansible_os_family == "RedHat"

- name: Add BWC enterprise repo
  become: yes
  shell: 'curl "{{ rpm_config_file_url }}" > {{ rpm_config_file_location }}'
  args:
    creates: "{{ rpm_config_file_location }}"
  register: added_bwc_rpm_repository
  when: ansible_os_family == "RedHat" and license is defined

- name: Update yum package cache
  become: yes
  yum:
    update_cache: true
  when: ansible_os_family == "RedHat" and added_rpm_repository|success
